// Auto-generated by scripts/export_backend_command_catalog.py
// Do not edit manually.

export const BACKEND_ACTIONS = {
    TEST_ASR: 'test_asr',
    TRANSLATE_TEXT: 'translate_text',
    TEST_TTS: 'test_tts',
    TEST_ALIGN: 'test_align',
    MERGE_VIDEO: 'merge_video',
    ANALYZE_VIDEO: 'analyze_video',
    TRANSCODE_VIDEO: 'transcode_video',
    DUB_VIDEO: 'dub_video',
    CHECK_AUDIO_FILES: 'check_audio_files',
    GENERATE_SINGLE_TTS: 'generate_single_tts',
    GENERATE_BATCH_TTS: 'generate_batch_tts',
    PREPARE_REFERENCE_AUDIO: 'prepare_reference_audio',
    WARMUP_TTS_RUNTIME: 'warmup_tts_runtime',
    SWITCH_RUNTIME_PROFILE: 'switch_runtime_profile',
} as const;

export type BackendAction = typeof BACKEND_ACTIONS[keyof typeof BACKEND_ACTIONS];
