from __future__ import annotations

import argparse
import json
import pathlib
import sys


ROOT_DIR = pathlib.Path(__file__).resolve().parents[1]
BACKEND_ROOT = ROOT_DIR / "services" / "media_pipeline"
if str(BACKEND_ROOT) not in sys.path:
    sys.path.insert(0, str(BACKEND_ROOT))

from vsm.app.contracts import serialize_backend_command_catalog


DEFAULT_OUTPUT = ROOT_DIR / "apps" / "desktop" / "ui" / "src" / "types" / "backendCommandCatalog.generated.json"
DEFAULT_ACTIONS_TS_OUTPUT = ROOT_DIR / "apps" / "desktop" / "ui" / "src" / "types" / "backendCommands.generated.ts"
DEFAULT_MARKDOWN_OUTPUT = ROOT_DIR / "docs" / "generated" / "backend-command-catalog.md"


def build_output_payload() -> dict[str, object]:
    commands = serialize_backend_command_catalog()
    return {
        "version": 1,
        "generated_from": "services/media_pipeline/vsm/app/contracts/command_catalog.py",
        "commands": commands,
    }


def build_actions_ts_content() -> str:
    payload = build_output_payload()
    command_names = [command["name"] for command in payload["commands"]]
    lines = [
        "// Auto-generated by scripts/export_backend_command_catalog.py",
        "// Do not edit manually.",
        "",
        "export const BACKEND_ACTIONS = {",
    ]
    for command_name in command_names:
        constant_name = command_name.upper().replace("-", "_")
        lines.append(f"    {constant_name}: '{command_name}',")
    lines.extend(
        [
            "} as const;",
            "",
            "export type BackendAction = typeof BACKEND_ACTIONS[keyof typeof BACKEND_ACTIONS];",
            "",
        ]
    )
    return "\n".join(lines)


def build_markdown_content() -> str:
    payload = build_output_payload()
    lines = [
        "# Backend Command Catalog",
        "",
        f"- Version: `{payload['version']}`",
        f"- Source: `{payload['generated_from']}`",
        "",
        "This file is generated by `scripts/export_backend_command_catalog.py`.",
        "",
    ]
    for command in payload["commands"]:
        lines.extend(
            [
                f"## `{command['name']}`",
                "",
                f"- Category: `{command['category']}`",
                f"- JSON Supported: `{command['json_supported']}`",
                f"- Description: {command['description']}",
                "",
                "| Argument | Required | Description |",
                "| --- | --- | --- |",
            ]
        )
        for arg in command["args"]:
            required = "Yes" if arg["required"] else "No"
            lines.append(f"| `{arg['name']}` | {required} | {arg['description']} |")
        lines.append("")
    return "\n".join(lines)


def write_catalog(output_path: pathlib.Path) -> None:
    payload = build_output_payload()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )


def write_actions_ts(output_path: pathlib.Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(build_actions_ts_content(), encoding="utf-8")


def write_markdown(output_path: pathlib.Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(build_markdown_content() + "\n", encoding="utf-8")


def check_catalog(output_path: pathlib.Path) -> int:
    expected = json.dumps(build_output_payload(), ensure_ascii=False, indent=2) + "\n"
    if not output_path.exists():
        print(f"Catalog file missing: {output_path}")
        return 1
    actual = output_path.read_text(encoding="utf-8")
    if actual != expected:
        print(f"Catalog file out of date: {output_path}")
        return 1
    print(f"Catalog file is up to date: {output_path}")
    return 0


def check_actions_ts(output_path: pathlib.Path) -> int:
    expected = build_actions_ts_content()
    if not output_path.exists():
        print(f"Action constants file missing: {output_path}")
        return 1
    actual = output_path.read_text(encoding="utf-8")
    if actual != expected:
        print(f"Action constants file out of date: {output_path}")
        return 1
    print(f"Action constants file is up to date: {output_path}")
    return 0


def check_markdown(output_path: pathlib.Path) -> int:
    expected = build_markdown_content() + "\n"
    if not output_path.exists():
        print(f"Markdown catalog file missing: {output_path}")
        return 1
    actual = output_path.read_text(encoding="utf-8")
    if actual != expected:
        print(f"Markdown catalog file out of date: {output_path}")
        return 1
    print(f"Markdown catalog file is up to date: {output_path}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Export backend command catalog for frontend consumption.")
    parser.add_argument("--output", type=pathlib.Path, default=DEFAULT_OUTPUT, help="Output JSON file path")
    parser.add_argument("--actions-ts-output", type=pathlib.Path, default=DEFAULT_ACTIONS_TS_OUTPUT, help="Output generated TypeScript action file path")
    parser.add_argument("--markdown-output", type=pathlib.Path, default=DEFAULT_MARKDOWN_OUTPUT, help="Output generated Markdown reference path")
    parser.add_argument("--check", action="store_true", help="Validate file contents instead of writing")
    args = parser.parse_args()

    output_path = args.output.resolve()
    actions_ts_output_path = args.actions_ts_output.resolve()
    markdown_output_path = args.markdown_output.resolve()
    if args.check:
        catalog_status = check_catalog(output_path)
        actions_status = check_actions_ts(actions_ts_output_path)
        markdown_status = check_markdown(markdown_output_path)
        return 0 if catalog_status == 0 and actions_status == 0 and markdown_status == 0 else 1

    write_catalog(output_path)
    write_actions_ts(actions_ts_output_path)
    write_markdown(markdown_output_path)
    print(f"Wrote backend command catalog: {output_path}")
    print(f"Wrote backend action constants: {actions_ts_output_path}")
    print(f"Wrote backend command markdown: {markdown_output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
